apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::697533197703:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-G709PP7HMH3C
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::697533197703:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-30T14:13:46Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1566"
  uid: 4d5aa235-0fbf-4324-a037-e094933fb161
